### ISSUE TITLE
Scraping courses I didn't create

### ISSUE THREAD

**Issue by mbenezra** [mikemcgowan/memrise-scraper#1]
Is it possible to scrape courses that were not created by me? I got the impression that memrise-scraper is limited to courses which I own. Am I right?

**Comment by mikemcgowan** [comment]
Yes and no.

There are two scrapers, one which scrapes a memrise course's 'levels' pages, and another which scrapes a memrise course's 'database' pages.

To run the 'database' scraper, you do need access to that database, which typically means you have to own the memrise course.

However, to run the 'levels' scraper, you don't need any particular access, because those pages are publicly visible. You can run the 'levels' scraper on its own like this:

```
scrapy crawl levels -s MEMRISE_MIN_LEVEL=1 -s MEMRISE_MAX_LEVEL=10
```

Hope this helps.
